### ISSUE TITLE
Python Version Inconsistency Between Local Dev and CI Environment

### ISSUE THREAD

**Issue by rhaegar325** [ACCESS-NRI/ACCESS-MOPPy#183]
### **Summary**
Tests pass locally on NCI Gadi (Python 3.11) but fail in GitHub Actions CI (Python 3.13) due to incompatible behavior in `netCDF4.stringtochar()` with `numpy.bytes_` objects.

---

### **Environment Comparison**

| Component | Local (NCI Gadi) | GitHub Actions CI | Status |
|-----------|------------------|-------------------|--------|
| Python | 3.11.13 | 3.13.11 | ❌ Mismatch |
| Environment | analysis3-25.09 | pixi (test env) | ❌ Different |
| netCDF4 | Older version | Newer version | ❌ Different behavior |
| Test Results | ✅ All pass (40/40) | ❌ 12 failed, 28 passed | ❌ Inconsistent |

---

### **Problem Description**

String coordinate handling in `CMIP6_CMORiser._write_string_variable()` works correctly on Python 3.11 but fails on Python 3.13 with:
```python
AttributeError: 'numpy.bytes_' object has no attribute 'encode'. Did you mean: 'decode'?
```

**Error Location:** `src/netCDF4/_netCDF4.pyx:6824` (inside `nc.stringtochar()`)

**Affected Tests:** All 12 string coordinate integration tests in `class TestCMIP6CMORiserWrite`

---

### **Root Cause**

In Python 3.13 + newer netCDF4, the internal implementation of `nc.stringtochar()` attempts to call `.encode()` on array elements. However, `numpy.bytes_` objects no longer have this method in newer numpy/Python versions.

**Current problematic code:**
```python
if is_scalar:
    values_array = np.array([values], dtype=values.dtype)  # dtype is numpy.bytes_
    char_array = nc.stringtochar(values_array)  # ❌ Fails in Python 3.13
    nc_var[:] = char_array[0]
```

---

### **Reproduction Steps**

1. **Local (passes):**
```bash
   # On NCI Gadi with Python 3.11
   module load conda/analysis3-25.09
   pytest tests/unit/test_base.py::TestCMIP6CMORiserWrite -v
   # Result: 40 passed ✅
```

2. **CI (fails):**
```bash
   # GitHub Actions with Python 3.13
   pixi run -e test pytest tests/unit/test_base.py::TestCMIP6CMORiserWrite
   # Result: 12 failed, 28 passed ❌
```

### **Recommendation**
Explicitly pin the Python version in the GitHub Actions environment so it matches the version used in the analysis3 modules.
